### ISSUE TITLE
Input resolution

### ISSUE THREAD

**Issue by LeungWaiHo** [LitingLin/SwinTrack#16]
Dear authors:
I noticed that the pretrain_img_size of swin-transformer-tiny is only 224 and input resolution of your SwinTrack Project is also 224.
I have a question "Could I increase the input resolution to 640 and keep swin-transformer-tiny as the backbone network?"
Thanks and look forward to your reply!

**Comment by LitingLin** [comment]
You can have a try. 

But the self-attention mechanism requires quadratic computation time with respect to the length of the input tokens. Efficiency is an issue.

**Comment by LeungWaiHo** [comment]
> You can have a try.
> 
> But the self-attention mechanism requires quadratic computation time with respect to the length of the input tokens. Efficiency is an issue.

Btw, I see your environment preparation "conda install anaconda", is it necessary?

**Comment by LitingLin** [comment]
anaconda is a meta package contains some popular packages. If you have the package listed in requirements.txt installed, you can skip this step.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: leungwilliams ***@***.***>
发送时间: Wednesday, December 15, 2021 10:56:58 AM
收件人: LitingLin/SwinTrack ***@***.***>
抄送: LitingLin ***@***.***>; Comment ***@***.***>
主题: Re: [LitingLin/SwinTrack] Input resolution (Issue #16)


You can have a try.

But the self-attention mechanism requires quadratic computation time with respect to the length of the input tokens. Efficiency is an issue.

Btw, I see your environment preparation "conda install anaconda", is it necessary?

―

**Comment by LeungWaiHo** [comment]
> anaconda is a meta package contains some popular packages. If you have the package listed in requirements.txt installed, you can skip this step. 获取 Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ 发件人: leungwilliams ***@***.***> 发送时间: Wednesday, December 15, 2021 10:56:58 AM 收件人: LitingLin/SwinTrack ***@***.***> 抄送: LitingLin ***@***.***>; Comment ***@***.***> 主题: Re: [LitingLin/SwinTrack] Input resolution (Issue #16) You can have a try. But the self-attention mechanism requires quadratic computation time with respect to the length of the input tokens. Efficiency is an issue. Btw, I see your environment preparation "conda install anaconda", is it necessary? ― You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLitingLin%2FSwinTrack%2Fissues%2F16%23issuecomment-994243443&data=04%7C01%7C%7C1b1dbea412dc49ad75e208d9bf769048%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751338214152163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FD4mLm0LuIHxfDYSHQ5LEyOnDDc8TIOIIKCxKe8agjk%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZNV6PPHVGUYSGDAGPJ5TLUQ77XVANCNFSM5KA4JHNQ&data=04%7C01%7C%7C1b1dbea412dc49ad75e208d9bf769048%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751338214152163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j8VOAuVXZgfNIoch3czZcaZ6Lg%2FAl1239InnkzucZ0I%3D&reserved=0>.

因为我在conda install anaconda时，solve environment一直在转圈圈， 其他的package倒没有问题，那我可以直接跳过conda install anaconda直接去安装下面的package？

**Comment by LitingLin** [comment]
保证requirements.txt里的package都安装好就可以

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: leungwilliams ***@***.***>
发送时间: Wednesday, December 15, 2021 11:28:48 AM
收件人: LitingLin/SwinTrack ***@***.***>
抄送: LitingLin ***@***.***>; Comment ***@***.***>
主题: Re: [LitingLin/SwinTrack] Input resolution (Issue #16)


anaconda is a meta package contains some popular packages. If you have the package listed in requirements.txt installed, you can skip this step. 获取 Outlook for iOShttps://aka.ms/o0ukef<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fo0ukef&data=04%7C01%7C%7C0c7b9e2dfd324073d1e708d9bf7b0221%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751357302084521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Fnn2f5nEW%2B3lHGrHHVmIS7tTVtLy%2F99M5hpeeFU5od8%3D&reserved=0>
…
________________________________ 发件人: leungwilliams @.> 发送时间: Wednesday, December 15, 2021 10:56:58 AM 收件人: LitingLin/SwinTrack @.> 抄送: LitingLin @.>; Comment @.> 主题: Re: [LitingLin/SwinTrack] Input resolution (Issue #16<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLitingLin%2FSwinTrack%2Fissues%2F16&data=04%7C01%7C%7C0c7b9e2dfd324073d1e708d9bf7b0221%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751357302094515%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lblPM7zMcZCT1GlGmBEEFWaNbfsYZXcUsmYWDVVGoIs%3D&reserved=0>) You can have a try. But the self-attention mechanism requires quadratic computation time with respect to the length of the input tokens. Efficiency is an issue. Btw, I see your environment preparation "conda install anaconda", is it necessary? D You are receiving this because you commented. Reply to this email directly, view it on GitHubhttps://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLitingLin%2FSwinTrack%2Fissues%2F16%23issuecomment-994243443&data=04%7C01%7C%7C1b1dbea412dc49ad75e208d9bf769048%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751338214152163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FD4mLm0LuIHxfDYSHQ5LEyOnDDc8TIOIIKCxKe8agjk%3D&reserved=0<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLitingLin%2FSwinTrack%2Fissues%2F16%23issuecomment-994243443&data=04%7C01%7C%7C0c7b9e2dfd324073d1e708d9bf7b0221%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751357302094515%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UUkL5bHPqYVe7L6WgV9AbqYcDn3ebo16hqFQljuuusk%3D&reserved=0>, or unsubscribehttps://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZNV6PPHVGUYSGDAGPJ5TLUQ77XVANCNFSM5KA4JHNQ&data=04%7C01%7C%7C1b1dbea412dc49ad75e208d9bf769048%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751338214152163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j8VOAuVXZgfNIoch3czZcaZ6Lg%2FAl1239InnkzucZ0I%3D&reserved=0<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZNV6PPHVGUYSGDAGPJ5TLUQ77XVANCNFSM5KA4JHNQ&data=04%7C01%7C%7C0c7b9e2dfd324073d1e708d9bf7b0221%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751357302104512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e%2FO%2F7XZViUyw0HCjEque%2BnZZeI93%2FFIK1Y0K6bRusyI%3D&reserved=0>.

因为我在conda install anaconda时，solve environment一直在转圈圈， 其他的package倒没有问题，那我可以直接跳过conda install anaconda直接去安装下面的package？

―
