### ISSUE TITLE
How to debug this code ?

### ISSUE THREAD

**Issue by Azong-HQU** [LitingLin/SwinTrack#21]
Hi, how to debug this code ?

**Comment by MaiAbboud** [comment]
you can change core/entry/train_args.py file like :
parser.add_argument('--method_name', default = 'SwinTrack', type=str, help='Method name')
parser.add_argument('--config_name', default = 'Tiny', type=str, help='Config name')
parser.add_argument('--mixin_config', default= 'got10k.yaml', type=str, action='append')
instead of instruction :
 python main.py SwinTrack Tiny --mixin_config got10k.yaml
and so on ....
